#' Visualize dialect groups with clustering methods
#'
#' Input a distance matrix, upon which clustering will be performed and projected unto a map.
#'
#' @param dist_mat A distance matrix as generated by the\code{\link{distance_matrix()}}.
#' @param kml_points A dataframe of kml points, as retrieved by \code{\link{get_points()}}.
#' @param kml_polygon A dataframe of kml polygons, as retrieved by \code{\link{get_polygons()}}.
#' @param cluster_num Number of clusters.
#' @param method The agglomeration method that is passed to hclust. This can be chosen from the following: "ward.D", "ward.D2", "single", "complete", "average" (= UPGMA), "mcquitty" (= WPGMA), "median" (= WPGMC) or "centroid" (= UPGMC).
#' @importFrom magrittr %>%
#' @import ggplot2
#' @return
#' @export
#'
#' @examples
cluster_map <- function(dist_mat, kml_points, kml_polygon, cluster_num, method){

  cluster_groups <- get_clusters(dist_mat, cluster_num, method)

  full_df <- merge(cluster_groups,
                kml_points,
                by.x="area",
                by.y="name")

  kml_points <- kml_points %>%
    dplyr::select(longitude, latitude)
  colnames(full_df) <- c("area", "grouping", "x", "y")
  colnames(kml_polygon) <- c("longitude", "latitude", "group")
  unique_indices <- !deldir::duplicatedxy(full_df[,3:4])
  full_df <- full_df[unique_indices,]

  ggplot(data = full_df,
         aes(x = x,
             y = y)) +
    ggvoronoi::geom_voronoi(
      mapping = aes(fill = as.factor(grouping)),
      alpha = 0.8,
      outline = kml_polygon,
      color = "grey") +
    theme(legend.position = "none") +
    xlab("longitude") +
    ylab("latitude")
}