# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkVowelConsonant <- function(w1, w2) {
    .Call(`_dialectR_checkVowelConsonant`, w1, w2)
}

distance_matrix <- function(dialect_data, funname, alignment_normalization = FALSE, delim_ = NULL) {
    .Call(`_dialectR_distance_matrix`, dialect_data, funname, alignment_normalization, delim_)
}

leven <- function(vec1, vec2, alignment_normalization = FALSE, delim_ = NULL) {
    .Call(`_dialectR_leven`, vec1, vec2, alignment_normalization, delim_)
}

split <- function(s, delimiter) {
    .Call(`_dialectR_split`, s, delimiter)
}

vc_leven <- function(vec1, vec2, alignment_normalization = FALSE, delim_ = NULL) {
    .Call(`_dialectR_vc_leven`, vec1, vec2, alignment_normalization, delim_)
}

vc_leven_align <- function(vec1, vec2) {
    .Call(`_dialectR_vc_leven_align`, vec1, vec2)
}

