# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_matrix <- function(dialect_data, funname, alignment_normalization = FALSE, delim = NULL) {
    .Call(`_dialectR_distance_matrix`, dialect_data, funname, alignment_normalization, delim)
}

#' Edit distance for Dialectometry
#'
#' An edit distance for use in Dialectometry. Allows for normalization by dividing alignment length, and for accommodating multiple responses with Bilbao distance.
#'
#' @param vec1 A vector of words.
#' @param vec2 A vector of words to be compared against.
#' @param alignment_normalization A logical value, indicating whether or not the difference scores are to be normalized by alignment length.
#' @param delim An optional delimiter, in situations where multiple responses exist in the data.
#' @return
#' @export
#'
#' @examples
#' # Example 1:
#' leven("hit", "hot/hit", alignment_normalization = TRUE, delim = "/")
leven <- function(vec1, vec2, alignment_normalization = FALSE, delim = NULL) {
    .Call(`_dialectR_leven`, vec1, vec2, alignment_normalization, delim)
}

#' VC-sensitive edit distance for Dialectometry
#'
#' An edit distance that is sensitive to vowel and consonant alignment. If the aligned segments are a vowel-consonant pair, the difference is penalized as a score of 2; if not, 1.  Allows for normalization by dividing alignment length, and for accommodating multiple responses with Bilbao distance.
#'
#' @param vec1 A vector of words.
#' @param vec2 A vector of words to be compared against.
#' @param alignment_normalization A logical value, indicating whether or not the difference scores are to be normalized by alignment length.
#' @param delim An optional delimiter, in situations where multiple responses exist in the data.
#' @return
#' @export
#'
#' @examples
#' # Example 1:
#' vc_leven("hit", "hot/hit", alignment_normalization = TRUE, delim = "/")
vc_leven <- function(vec1, vec2, alignment_normalization = FALSE, delim = NULL) {
    .Call(`_dialectR_vc_leven`, vec1, vec2, alignment_normalization, delim)
}

